config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      patch 'set_best', on: :member, to: 'answers#best'
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  skip_before_action :authenticate_user!, only: %i[index show]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    question
    @answer = Answer.new(question: @question)
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit
    question
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    if can? :destroy, question
      question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      redirect_to question, alert: 'You are not allowed to delete this question.'
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(
      :title, :body, files: [], links_attributes: %i[name url _destroy], reward_attributes: %i[title image]
    )
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('QuestionsChannel', { question: @question })
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.question-errors
  = render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  == render 'shared/partial_form_question', f: f

app/views/questions/_question.html.slim
.card.mb-4.question(data-question-id=question.id)
    .card-body
      h2.card-title = question.title
      p.card-text = question.body

      = render 'shared/link', object: question

      - if question.files.attached?
        == render 'shared/file', object: question
      
      - if question.reward
        .reward
          h5 Reward
          p = question.reward.title
          - if question.reward.image.attached?
            = image_tag question.reward.image

      - if can?(:update, question)
        .btn-group
          = link_to 'Edit', '#', class: 'btn btn-primary edit-question-link', data: { question_id: question.id }
          = link_to 'Delete', question_path(question), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }

        .question-errors
          = render 'shared/errors', resource: question
        = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" }, local: false, turbo: false do |f|
          == render 'shared/partial_form_question', f: f
      
      .question-rating
        = render 'shared/vote', object: question

      = render 'shared/comments', object: question
      div id="question_new_comment#{question.id}"
        = render 'shared/comment_form', commentable: question

app/views/questions/index.html.slim
h1.text-center.mt-5 All Questions

= link_to 'Ask question', new_question_path, class: 'btn btn-primary mb-3'

.row.question-list
  - @questions.each do |question|
    .col-sm-4
      .card.mb-3
        .card-body
          h5.card-title = link_to question.title, question_path(question), class: 'card-link'
          p.card-text = truncate(question.body, length: 30)

app/views/questions/new.html.slim
.card.mb-3
  .card-header
    h1 New Question
  .card-body
    = render 'form'

app/views/questions/show.html.slim
.container
  h2.mt-4 Question Details

  = render @question

  .row.justify-content-center
    .col-md-7
      h4.mt-4 Answers
      .mt-4.mb-2.answers
        = render @question.answers

      - if user_signed_in?
        .card-body
          .answer-errors
            = render 'shared/errors', resource: @answer
          = form_with model: [@question, @answer], class: 'new-answer', local: false, turbo: false do |f|
            == render 'shared/partial_form_answer', f: f

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>