config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      patch 'set_best', on: :member, to: 'answers#best'
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  default_scope { order(best: :desc) }
  scope :best, -> { where(best: true) }

  def set_best!
    transaction do
      unless best?
        question.answers.best.update_all(best: false) if question.answers.best.any?
        update!(best: true)
        question.reward&.update!(user: user)
      end
    end
  end

  private

  def best?
    best
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  skip_before_action :authenticate_user!, only: [:show]

  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question = question
    @answer.save
  end

  def update
    answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def best
    authorize! :best, answer
    answer.set_best!
    @question = @answer.question
  end

  private

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : Question.new
  end

  helper_method :question

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("answers_for_question_#{@question.id}", { answer: @answer, question: @question })
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer-container
  div id="answer_#{answer.id}" class="card mb-3"
    - if answer.best
      p.text-success.font-weight-bold Best answer

    h3.card-title= answer.body
        
    = render 'shared/link', object: answer

    - if answer.files.attached?
      == render 'shared/file', object: answer

    - if can?(:best, answer) && !answer.best
      p= link_to 'Set as best', "/answers/#{answer.id}/set_best", method: :patch, remote: true

    - if can?(:update, answer)
      .btn-group
        p= link_to 'Edit', '#', class: 'btn btn-primary edit-answer-link', data: { answer_id: answer.id }
        p= link_to 'Delete', answer_path(answer), class: 'btn btn-danger', method: :delete, remote: true, data: { confirm: 'Are you sure?' }
        
      .answer-errors
        = render 'shared/errors', resource: answer
          
      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false, turbo: false do |f|
        == render 'shared/partial_form_answer', f: f

    .answer-rating
      = render 'shared/vote', object: answer

    = render 'shared/comments', object: answer
    div id="answer_new_comment#{answer.id}"
      = render 'shared/comment_form', commentable: answer

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer .nested-fields input[type=text], .new-answer .nested-fields input[type=url]').val('');
  $('.new-answer .nested-fields').hide();
<% end %>

app/views/answers/destroy.js.erb
$("#answer_<%= @answer.id %>").remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>