config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      patch 'set_best', on: :member, to: 'answers#best'
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :create, [Question, Answer]
    can :add_comment, [Question, Answer]
    can %i[update destroy], [Question, Answer] do |resource|
      user.author_of?(resource)
    end
    can %i[vote_up vote_down], [Question, Answer] do |votable|
      !user.author_of?(votable)
    end
    can :best, Answer do |answer|
      user.author_of?(answer.question)
    end
    can :destroy, ActiveStorage::Attachment do |attachment|
      user.author_of?(attachment.record)
    end
    can :destroy, Link do |link|
      user.author_of?(link.linkable)
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  default_scope { order(best: :desc) }
  scope :best, -> { where(best: true) }

  def set_best!
    transaction do
      unless best?
        question.answers.best.update_all(best: false) if question.answers.best.any?
        update!(best: true)
        question.reward&.update!(user: user)
      end
    end
  end

  private

  def best?
    best
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validate :url_format_valid?

  def gist?
    url.include?('gist.github.com')
  end

  private

  def url_format_valid?
    uri = URI.parse(url)
    unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
      errors.add(:url, 'is not a valid URL')
    end
  rescue URI::InvalidURIError
    errors.add(:url, 'is not a valid URL')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  has_one_attached :image

  validates :title, presence: true
  validate :attachment_content_type

  private

  def attachment_content_type
    return unless image.attached? && !image.content_type.in?(%w[image/jpeg image/png])

    errors.add(:image, 'must be a JPEG or PNG')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[github vkontakte]

  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :rewards, dependent: :nullify
  has_many :authorizations, dependent: :destroy

  def self.find_for_oauth(auth)
    FindForOauth.new(auth).call
  end

  def author_of?(resource)
    resource.user_id == id
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[votable_id votable_type] }
  validates :value, inclusion: { in: [1, 0, -1] }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  skip_before_action :authenticate_user!, only: [:show]

  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question = question
    @answer.save
  end

  def update
    answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def best
    authorize! :best, answer
    answer.set_best!
    @question = @answer.question
  end

  private

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : Question.new
  end

  helper_method :question

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("answers_for_question_#{@question.id}", { answer: @answer, question: @question })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :gon_user

  private

  def gon_user
    gon.current_user = current_user
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  check_authorization unless: :devise_controller?
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  authorize_resource

  def destroy
    file.purge
  end

  private

  def file
    @file ||= ActiveStorage::Attachment.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  authorize_resource

  def destroy
    link.destroy
  end

  private

  def link
    @link ||= Link.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  skip_before_action :authenticate_user!, only: %i[index show]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    question
    @answer = Answer.new(question: @question)
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit
    question
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    if can? :destroy, question
      question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      redirect_to question, alert: 'You are not allowed to delete this question.'
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(
      :title, :body, files: [], links_attributes: %i[name url _destroy], reward_attributes: %i[title image]
    )
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('QuestionsChannel', { question: @question })
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  skip_authorization_check

  def index; end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-5">
  <hr class="my-4">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <p><%= current_year %></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">QNA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rewards', rewards_path, class: "nav-link" %>    
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">
    <meta name="github-token" content="<%= ENV['GITHUB_TOKEN'] %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= include_gon %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_comment_form.html.slim
- if user_signed_in?
  = form_with(model: [commentable, Comment.new], url: polymorphic_path([:add_comment, commentable]), local: false, remote: true ) do |f|
    .form-group
      = f.label :body, "Add comment"
      = f.text_area :body, class: 'form-control', id: "comment_body_#{commentable.class.to_s.downcase}_#{commentable.id}"
    .form-group
      = f.submit "Add comment", class: 'btn btn-primary'

app/views/shared/_comments.html.slim
- if object.comments.any?
  .comment-errors(id="comment-errors-#{object.class.to_s.downcase}-#{object.id}")
  .comments(data-commentable-type="#{object.class}" data-commentable-id="#{object.id}")
    h5.mt-3.mb-3 Comments:
    - object.comments.each do |comment|
      .card.mb-2
        .card-body
          h6.card-text = comment.body

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_file.html.slim
- object.files.each do |file|
  div id="file_#{file.id}"
    p
      = link_to file.filename.to_s, url_for(file)
      - if can?(:destroy, file)
        = link_to 'X', file_path(file), method: :delete, remote: true, class: 'delete-link'

app/views/shared/_link.html.slim
.links
  - if object.links.any?
    p Links:
    ul
      - object.links.each do |link|
        li id="link_#{link.id}"
          = link_to link.name, link.url, class: (link.gist? ? 'gist-link' : '')
          - if can?(:destroy, link)
            = link_to 'X', link_path(link), method: :delete, remote: true, class: 'delete-link'

app/views/shared/_link_fields.html.slim
.nested-fields.card.border.p-2.mb-2 
  .form-group.mb-
    = f.label :name, 'Link name', class: 'form-label'
    = f.text_field :name, class: 'form-control form-control-sm'

  .form-group.mb-1
    = f.label :url, class: 'form-label'
    = f.text_field :url, class: 'form-control form-control-sm'

  = link_to_remove_association 'Remove Link', f

app/views/shared/_link_form.html.slim
div
  = link_to_add_association 'Add Link', f, :links, partial: 'shared/link_fields'

app/views/shared/_partial_form_answer.html.slim
h4.mt-4 Answer the question

= f.label :body
= f.text_area :body, class: 'form-control', rows: 4

= f.label :files
= f.file_field :files, multiple: true, class: 'form-control'

p 
  = render 'shared/link_form', f: f

= f.submit 'Answer', class: 'btn btn-primary mt-3'

app/views/shared/_partial_form_question.html.slim
.form-group
  = f.label :title
  = f.text_field :title, class: 'form-control'

.form-group
  = f.label :body
  = f.text_area :body, class: 'form-control'

p
  .form-group
    = f.label :files
    = f.file_field :files, multiple: true, class: 'form-control'

p
  = render 'shared/link_form', f: f

p
  = render 'shared/reward_form', f: f

= f.submit 'Ask', class: 'btn btn-primary'

app/views/shared/_rating.html.slim
p
  | Rating:
  span.rating-count= object.rating

app/views/shared/_reward_form.html.slim
.card.mb-3
  .card-body
    .reward-form
      = f.fields_for :reward do |r|
        .form-group
          = r.label :title, "Reward title"
          = r.text_field :title, class: 'form-control'
        .form-group
          = r.label :image, "Reward image"
          = r.file_field :image, class: 'form-control'

app/views/shared/_vote.html.slim
.votes
  - if can?(:vote_up, object)
    .btn-group
      = button_to '👍', polymorphic_path([:vote_up, object]), method: :post, remote: true, data: { type: 'json' }
      = button_to '👎', polymorphic_path([:vote_down, object]), method: :post, remote: true, data: { type: 'json' }

  = render 'shared/rating', object: object